#プロジェクトセットアップ用のdocker-compose
services:
  base:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
      target: base
    image: node_base
    volumes:
      - type: bind
        source: ./react
        target: /app
    working_dir: /app
    command: npm create vite@latest . -- --template react-swc-ts

  module-install:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
      target: base
    image: node_base
    volumes:
      - type: bind
        source: ./react
        target: /app
    working_dir: /app
    command: npm install

  installer:
    image: node_base
    volumes:
      - type: bind
        source: ./react
        target: /app
    working_dir: /app
    entrypoint: npm install
    command: axios react-router-dom howler

  installer-dev:
    image: node_base
    volumes:
      - type: bind
        source: ./react
        target: /app
    working_dir: /app
    entrypoint: npm install -D
    command: vite-tsconfig-paths vitest happy-dom @vitest/coverage-v8 @testing-library/react @testing-library/user-event @testing-library/jest-dom
