services:
  api:
    container_name: python-api
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    tty: true
    env_file:
      - ./docker/backend/.env
    environment:
      - TZ=Asia/Tokyo
  front:
    container_name: react-front
    build:
      context: .
      target: dev
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - type: bind
        source: ./react
        target: /app
      - type: volume
        source: node-modules-volume
        target: /src/node_modules
    ports:
      - 5173:5173
      - 4173:4173
    tty: true
    env_file:
      - ./docker/react/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node-modules-volume:
